# NOTE: Generated By HttpRunner v3.1.4
# FROM: har\mubu_login.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseMubuLogin(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/")
            .get("https://mubu.com/")
            .with_headers(
                **{
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "none",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "9f03ab55-052e-44e7-89e1-83c2feaef92c",
                    "csrf_token": "ed88be3a-ed4b-48e3-96d1-949d93298a2f",
                    "SESSION": "106c02e8-cc86-45c2-8992-879c5c5dcb95",
                    "language": "en-US",
                    "country": "US",
                    "_ga": "GA1.2.1434520657.1614511773",
                    "_gid": "GA1.2.197959454.1614511773",
                    "_gat": "1",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1614511773",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "reg_prepareId": "177e866a718-177e866a716-49d4-acc5-540c1ab98525",
                    "reg_focusId": "85f10748-e7e8-49d4-acc5-177e867095d",
                    "SLARDAR_WEB_ID": "8caa430e-59f9-4a33-8f6d-66246b007ee7",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1614511818",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/login")
            .get("https://mubu.com/login")
            .with_headers(
                **{
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "9f03ab55-052e-44e7-89e1-83c2feaef92c",
                    "csrf_token": "ed88be3a-ed4b-48e3-96d1-949d93298a2f",
                    "SESSION": "106c02e8-cc86-45c2-8992-879c5c5dcb95",
                    "language": "en-US",
                    "country": "US",
                    "_ga": "GA1.2.1434520657.1614511773",
                    "_gid": "GA1.2.197959454.1614511773",
                    "_gat": "1",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1614511773",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "reg_prepareId": "177e866a718-177e866a716-49d4-acc5-540c1ab98525",
                    "reg_focusId": "85f10748-e7e8-49d4-acc5-177e867095d",
                    "SLARDAR_WEB_ID": "6a2b9c09-3066-4349-b84c-f9ec74cb783e",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1614511828",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/api/reg/check_phone")
            .post("https://mubu.com/api/reg/check_phone")
            .with_headers(
                **{
                    "content-length": "17",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "x-requested-with": "XMLHttpRequest",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36",
                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/login",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "9f03ab55-052e-44e7-89e1-83c2feaef92c",
                    "csrf_token": "ed88be3a-ed4b-48e3-96d1-949d93298a2f",
                    "SESSION": "106c02e8-cc86-45c2-8992-879c5c5dcb95",
                    "language": "en-US",
                    "country": "US",
                    "_ga": "GA1.2.1434520657.1614511773",
                    "_gid": "GA1.2.197959454.1614511773",
                    "_gat": "1",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1614511773",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "SLARDAR_WEB_ID": "ed4db32a-7611-430c-b3a5-f81c33e9f327",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1614511830",
                    "reg_prepareId": "177e86775c4-177e86774da-45c0-8ba3-18fbe860489a",
                    "reg_focusId": "d0f6d74b-da4e-45c0-8ba3-177e8677a18",
                }
            )
            .with_data({"phone": "18883285613"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/login/password")
            .get("https://mubu.com/login/password")
            .with_headers(
                **{
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://mubu.com/login",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "9f03ab55-052e-44e7-89e1-83c2feaef92c",
                    "csrf_token": "ed88be3a-ed4b-48e3-96d1-949d93298a2f",
                    "SESSION": "106c02e8-cc86-45c2-8992-879c5c5dcb95",
                    "language": "en-US",
                    "country": "US",
                    "_ga": "GA1.2.1434520657.1614511773",
                    "_gid": "GA1.2.197959454.1614511773",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1614511773",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "SLARDAR_WEB_ID": "ed4db32a-7611-430c-b3a5-f81c33e9f327",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1614511830",
                    "reg_prepareId": "177e86775c4-177e86774da-45c0-8ba3-18fbe860489a",
                    "reg_focusId": "d0f6d74b-da4e-45c0-8ba3-177e8677a18",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/api/login/submit")
            .post("https://mubu.com/api/login/submit")
            .with_headers(
                **{
                    "content-length": "52",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "x-requested-with": "XMLHttpRequest",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36",
                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/login/password",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "9f03ab55-052e-44e7-89e1-83c2feaef92c",
                    "csrf_token": "ed88be3a-ed4b-48e3-96d1-949d93298a2f",
                    "SESSION": "106c02e8-cc86-45c2-8992-879c5c5dcb95",
                    "language": "en-US",
                    "country": "US",
                    "_ga": "GA1.2.1434520657.1614511773",
                    "_gid": "GA1.2.197959454.1614511773",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1614511773",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "reg_prepareId": "177e86775c4-177e86774da-45c0-8ba3-18fbe860489a",
                    "reg_focusId": "d0f6d74b-da4e-45c0-8ba3-177e8677a18",
                    "_gat": "1",
                    "SLARDAR_WEB_ID": "16154dce-92a6-4b77-9fdd-3a14559c2a13",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1614511839",
                }
            )
            .with_data(
                {"phone": "18883285613", "password": "yxzhy171122", "remember": "true"}
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/app")
            .get("https://mubu.com/app")
            .with_headers(
                **{
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://mubu.com/login/password",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "9f03ab55-052e-44e7-89e1-83c2feaef92c",
                    "csrf_token": "ed88be3a-ed4b-48e3-96d1-949d93298a2f",
                    "SESSION": "106c02e8-cc86-45c2-8992-879c5c5dcb95",
                    "language": "en-US",
                    "country": "US",
                    "_ga": "GA1.2.1434520657.1614511773",
                    "_gid": "GA1.2.197959454.1614511773",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1614511773",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "reg_prepareId": "177e86775c4-177e86774da-45c0-8ba3-18fbe860489a",
                    "reg_focusId": "d0f6d74b-da4e-45c0-8ba3-177e8677a18",
                    "_gat": "1",
                    "SLARDAR_WEB_ID": "16154dce-92a6-4b77-9fdd-3a14559c2a13",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1614511839",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNDYyOTA0IiwiZXhwIjoxNjE3MTAzODUwLCJpYXQiOjE2MTQ1MTE4NTB9.PhYjmVfLf0OX3gA3p5gdmvPToOfxDUakqJ5NvsIx_-KUEJijgJRMOApBp6PQ4fF0Czv01D4stwHfnqvwjquWrA",
                    "user_persistence": "6ff44bfe-6ebd-4669-bce8-67ba1e300a08",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseMubuLogin().test_start()
