# NOTE: Generated By HttpRunner v4.2.0
# FROM: testcases\login_test.json
from httprunner import HttpRunner, Config, Step, RunRequest


class TestCaseLoginTest(HttpRunner):

    config = Config("testcase description")

    teststeps = [
        Step(
            RunRequest("")
            .post("http://192.168.0.1/login/Auth")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Content-Length": "66",
                    "Content-Type": "application/json; charset=UTF-8",
                    "Host": "192.168.0.1",
                    "Origin": "http://192.168.0.1",
                    "Referer": "http://192.168.0.1/login.html",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36",
                    "X-Requested-With": "XMLHttpRequest",
                }
            )
            .with_cookies(
                **{
                    "_:USERNAME:_": "38c00fd074968175202aaf6e5eaee1ba",
                    "bLanguage": "en",
                }
            )
            .with_json(
                {"password": "25D55AD283AA400AF464C76D713C07AD", "userName": "admin"}
            )
            .validate()
            .assert_equal("status_code", 200, "assert response status code")
            .assert_equal(
                'headers."Content-Type"',
                "text/html",
                "assert response header Content-Type",
            )
        ),
    ]


if __name__ == "__main__":
    TestCaseLoginTest().test_start()
