global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost: 9093

rule_files:
  - rules/*.rules

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'node_exporter'
    static_configs:
    - targets: ['127.0.0.1:9100']
  - job_name: 'mysql'
    static_configs:
    - targets: ['127.0.0.1:9104']
  - job_name: 'cadvisor'
    static_configs:
    - targets: ['127.0.0.1:8091']